<?php
/*<!--<wikitext>-->
{{Extension
|name        = XYZ
|status      = beta
|type        = other
|author      = [[user:jldupont|Jean-Lou Dupont]]
|image       =
|version     = See SVN ($Id$)
|update      =
|mediawiki   = tested on 1.10 but probably works with a earlier versions
|download    = [http://bizzwiki.googlecode.com/svn/trunk/BizzWiki/extensions/XYZ/ SVN]
|readme      =
|changelog   =
|description = 
|parameters  =
|rights      =
|example     =
}}
<!--@@
{{#autoredirect: Extension|{{#noext:{{SUBPAGENAME}} }} }}
== File Status ==
This section is only valid when viewing the page in a BizzWiki environment.
<code>(($#extractmtime|@@mtime@@$))  (($#extractfile|@@file@@$))</code>

Status: (($#comparemtime|<b>File system copy is newer - [{{fullurl:{{NAMESPACE}}:{{PAGENAME}}|action=reload}} Reload] </b>|Up to date$))
@@-->
== Purpose==


== Features ==


== Dependancy ==
* [[Extension:NamespaceManager|NamespaceManager extension]]

== Installation ==
To install independantly from BizzWiki:
* Declare the namespace 'NS_EXT' in 'LocalSettings.php' (see example below)
** Add to the 'extra namespaces' global variable
* Download & Install [[Extension:NamespaceManager]] extension
* Dowload all this extension's files and place in the desired directory
* Apply the following changes to 'LocalSettings.php':
<source lang=php>
require('extensions/NamespaceManager/NamespaceManager.php'); # must already be present since
                                                             # extension NamespaceManager should be installed

define('NS_EXT', 100);                                       # choose a free ID >=100 
$wgExtraNamespaces[NS_EXT]   = 'Ext';                        # [[Ext:XYZ]]
$wgCanonicalNamespaceNames[NS_EXT] = 'Ext'; 
require('extensions/ExtensionManager/ExtensionManager_stub.php');
</source>

== History ==

== See Also ==
This extension is part of the [[Extension:BizzWiki|BizzWiki Platform]].

== Code ==
<!--</wikitext>--><source lang=php>*/

// Do a quick check and echo a useful message
// if the dependent extension is not installed.
if (class_exists('NamespaceManagers'))
{
$wgExtensionCredits['other'][] = array( 
	'name'    	=> 'ExtensionManager',
	'version' 	=> NamespaceManagers::getRevisionId('$Id$'),
	'author'  	=> 'Jean-Lou Dupont',
	'description' => "Provides installation and maintenance for MediaWiki extensions. ", 
	'url' 		=> NamespaceManagers::getFullUrl(__FILE__),	
);

require('ExtensionManager.i18n.php');
NamespaceManagers::register( NS_EXT, 'ExtensionManager', dirname(__FILE__).'/ExtensionManager.php' );

// required for proper operation of 'log' function.
#NamespaceManagers::setupMessages();
						
// This file actually contains the list of extensions installed.
// The file gets updated dynamically by ExtensionManager.
// DO NOT EDIT THIS FILE MANUALLY!
#@require('_List.php');
}
else
{
	echo '<b>ExtensionManager:</b> NamespaceManager extension not installed.<br/>';	
}
//</source>
